### PR TITLE
Add PufferPanel

### PR DESCRIPTION
**Pull request by oskardotglobal**
PufferPanel is a simplistic, free and open-source game server management panel. It fully supports Minecraft servers out of the box.

### CODE REVIEW

**Comment by NordicGamerFE** [comment]
Remove mention of other panels

**Review by lrmtheboss — CHANGES_REQUESTED** [review]
As @NordicGamerFE said, Remove the mention of other panels in the description

**Comment by oskardotglobal** [comment]
Ok, I did.

**Review by lrmtheboss — APPROVED** [review]
Looks Good

**Pull request merged**
